### ISSUE TITLE
Game hangs on launch

### ISSUE THREAD

**Issue by saavor** [glisco03/isometric-renders#30]
The game hangs on launch with the isometric renders mod installed. The game just freezes and doesn't close. No errors are logged.

OS: MacOS: 12.4
Minecraft Version: 1.19
Fabric Version: 0.14.7
Isometric Renders Version: 0.3.1

**Comment by haykam821** [comment]
I can reproduce this issue with Isometric Renders 0.3.0 for Minecraft 1.18.2.

**Comment by saavor** [comment]
I also have sodium installed, I haven't tested it but it could potentially be a problem.

**Comment by saavor** [comment]
> I also have sodium installed, I haven't tested it but it could potentially be a problem.

I just tested it and no, removing sodium has no effect.

**Comment by gliscowo** [comment]
This should be fixed (at least on macOS) in [0.3.2](https://modrinth.com/mod/isometric-renders/version/3q2NIbD8). If not, you can force-disable AWT intialization with the `-Disometric-renders.disableClipboard=true` JVM flag
Cheers

**Comment by haykam821** [comment]
This issue persists with Isometric Renders 0.3.1 for Minecraft 1.18.2 because the fix was not ported from Minecraft 1.19.
